#!/usr/bin/env python3
"""
led_config_gen.py — Generador de led_indicators.h para el keymap zsa-moonlander.

Lee:
  - led_config/led_config.json   → configuración del usuario
  - mapping.json                 → obtiene invert_layout

Genera:
  - keymaps/zsa-moonlander/led_indicators.h

Llamado automáticamente por convert_moonlander.py cuando
hasToOverrideLedConfig = true en mapping.json.
"""

import json
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR   = Path(__file__).parent                              # led_config/
PORTING_DIR  = SCRIPT_DIR.parent                                  # porting_zsa-moonlander/
KEYBOARD_DIR = PORTING_DIR.parent                                 # keyboards/chosfox/geonixr2/
KEYMAP_DIR   = KEYBOARD_DIR / "keymaps" / "zsa-moonlander"

LED_CONFIG_FILE = SCRIPT_DIR / "led_config.json"
MAPPING_FILE    = PORTING_DIR / "mapping.json"
OUTPUT_FILE     = KEYMAP_DIR / "led_indicators.h"

# ---------------------------------------------------------------------------
# LED matrix — must match g_led_config in geonixr2.c
# ---------------------------------------------------------------------------
NO_LED = 255

LED_MATRIX = [
    [  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
    [ 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
    [ 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
    [ 36, 37, 38, 39, 40, NO_LED, 41, 42, 43, 44, 45, 46],
]

ROWS = 4
COLS = 12

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def resolve_led(visual_row: int, visual_col: int, invert: bool) -> int:
    """
    Convierte coordenadas visuales [fila, col] a índice LED del hardware.
    Si invert_layout=True, invierte filas y columnas antes de buscar en la matriz.
    Devuelve NO_LED (255) si la posición no tiene LED.
    """
    if invert:
        hw_row = (ROWS - 1) - visual_row
        hw_col = (COLS - 1) - visual_col
    else:
        hw_row = visual_row
        hw_col = visual_col

    if hw_row < 0 or hw_row >= ROWS or hw_col < 0 or hw_col >= COLS:
        return NO_LED

    return LED_MATRIX[hw_row][hw_col]


def validate_pos(pos, name: str, invert: bool) -> int:
    """Valida y resuelve una posición. Aborta si es inválida o NO_LED."""
    if not isinstance(pos, list) or len(pos) != 2:
        sys.exit(f"ERROR: '{name}.pos' debe ser [fila, col]. Valor: {pos}")
    row, col = pos
    if not (0 <= row < ROWS and 0 <= col < COLS):
        sys.exit(f"ERROR: '{name}.pos' fuera de rango [0-{ROWS-1}, 0-{COLS-1}]. Valor: {pos}")
    idx = resolve_led(row, col, invert)
    if idx == NO_LED:
        sys.exit(f"ERROR: '{name}.pos' {pos} resulta en NO_LED tras aplicar invert_layout={invert}. Elige otra posición.")
    return idx


def resolve_battery_leds(leds_cfg: list, invert: bool) -> list:
    """
    Resuelve el array de posiciones de la barra de batería.
    Descarta silenciosamente posiciones NO_LED.
    """
    result = []
    for pos in leds_cfg:
        if not isinstance(pos, list) or len(pos) != 2:
            print(f"  WARN: battery_bar.leds — posición inválida ignorada: {pos}")
            continue
        row, col = pos
        if not (0 <= row < ROWS and 0 <= col < COLS):
            print(f"  WARN: battery_bar.leds — posición fuera de rango ignorada: {pos}")
            continue
        idx = resolve_led(row, col, invert)
        if idx == NO_LED:
            # Descarte silencioso — es el comportamiento esperado para el hueco del spacebar
            continue
        result.append(idx)
    return result


def validate_layer(layer, name: str) -> int:
    if not isinstance(layer, int) or not (0 <= layer <= 15):
        sys.exit(f"ERROR: '{name}' debe ser un número de capa entre 0 y 15. Valor: {layer}")
    return layer


def validate_threshold(val, name: str) -> int:
    if not isinstance(val, int) or not (0 <= val <= 100):
        sys.exit(f"ERROR: '{name}' debe ser un porcentaje entre 0 y 100. Valor: {val}")
    return val

# ---------------------------------------------------------------------------
# Generador principal
# ---------------------------------------------------------------------------

def generate(cfg: dict, invert: bool) -> str:
    lines = []
    lines.append("// AUTO-GENERATED by led_config_gen.py — DO NOT EDIT")
    lines.append("// Source: porting_zsa-moonlander/led_config/led_config.json")
    lines.append("#pragma once")
    lines.append("")

    # ---- Connection LEDs ----
    conn = cfg.get("connection_leds", {})
    lines.append("// ============================================================")
    lines.append("// Connection mode LED indices")
    lines.append("// (undef first to override keyboard-level config.h defaults)")
    lines.append("// ============================================================")

    usb_idx  = validate_pos(conn.get("usb",  {}).get("pos"), "connection_leds.usb",  invert)
    ble1_idx = validate_pos(conn.get("ble1", {}).get("pos"), "connection_leds.ble1", invert)
    ble2_idx = validate_pos(conn.get("ble2", {}).get("pos"), "connection_leds.ble2", invert)
    ble3_idx = validate_pos(conn.get("ble3", {}).get("pos"), "connection_leds.ble3", invert)
    g24_idx  = validate_pos(conn.get("g24",  {}).get("pos"), "connection_leds.g24",  invert)

    for name, val in [("LED_USB_INDEX", usb_idx), ("LED_BLE_1_INDEX", ble1_idx),
                      ("LED_BLE_2_INDEX", ble2_idx), ("LED_BLE_3_INDEX", ble3_idx),
                      ("LED_2P4G_INDEX", g24_idx)]:
        lines.append(f"#undef  {name}")
        lines.append(f"#define {name} {val}")
    lines.append("")

    # ---- BLE names ----
    ble1_name = conn.get("ble1", {}).get("name", "BLE Device 1")
    ble2_name = conn.get("ble2", {}).get("name", "BLE Device 2")
    ble3_name = conn.get("ble3", {}).get("name", "BLE Device 3")
    lines.append("// BLE profile names")
    for name, val in [("USER_BLE1_NAME", ble1_name), ("USER_BLE2_NAME", ble2_name),
                      ("USER_BLE3_NAME", ble3_name)]:
        lines.append(f"#undef  {name}")
        lines.append(f'#define {name} "{val}"')
    lines.append("")

    # ---- State indicator LEDs ----
    lines.append("// ============================================================")
    lines.append("// State indicator LEDs")
    lines.append("// ============================================================")

    cap_idx  = validate_pos(cfg.get("caps_lock_led",   {}).get("pos"), "caps_lock_led",   invert)
    win_idx  = validate_pos(cfg.get("win_lock_led",    {}).get("pos"), "win_lock_led",    invert)
    batt_idx = validate_pos(cfg.get("battery_low_led", {}).get("pos"), "battery_low_led", invert)

    for name, val in [("LED_CAP_INDEX", cap_idx), ("LED_WIN_L_INDEX", win_idx),
                      ("LED_BATT_INDEX", batt_idx)]:
        lines.append(f"#undef  {name}")
        lines.append(f"#define {name} {val}")
    lines.append("")

    # ---- Battery bar ----
    lines.append("// ============================================================")
    lines.append("// Battery bar (QK_BAT display)")
    lines.append("// ============================================================")

    bar = cfg.get("battery_bar", {})
    low_thr = validate_threshold(bar.get("low_threshold", 20), "battery_bar.low_threshold")
    med_thr = validate_threshold(bar.get("med_threshold", 50), "battery_bar.med_threshold")

    if low_thr >= med_thr:
        sys.exit(f"ERROR: battery_bar.low_threshold ({low_thr}) debe ser menor que med_threshold ({med_thr})")

    bar_leds = resolve_battery_leds(bar.get("leds", []), invert)
    if not bar_leds:
        sys.exit("ERROR: battery_bar.leds no contiene ninguna posición válida con LED.")

    bar_count = len(bar_leds)
    bar_array = ", ".join(str(i) for i in bar_leds)

    lines.append(f"#undef  BATTERY_LED_COUNT")
    lines.append(f"#define BATTERY_LED_COUNT     {bar_count}")
    lines.append(f"#undef  BATTERY_LED_ARRAY")
    lines.append(f"#define BATTERY_LED_ARRAY     {{{bar_array}}}")
    lines.append(f"#undef  BATTERY_LOW_THRESHOLD")
    lines.append(f"#define BATTERY_LOW_THRESHOLD {low_thr}")
    lines.append(f"#undef  BATTERY_MED_THRESHOLD")
    lines.append(f"#define BATTERY_MED_THRESHOLD {med_thr}")
    lines.append("")

    # ---- Fn layers ----
    lines.append("// ============================================================")
    lines.append("// Layers that activate the connection mode indicator (Fn-held)")
    lines.append("// ============================================================")

    fn_cfg    = conn.get("indicator_layers", {})
    fn_layers = fn_cfg.get("layers", [])
    if not fn_layers:
        sys.exit("ERROR: connection_leds.indicator_layers.layers está vacío.")

    validated = [validate_layer(l, f"indicator_layers.layers[{i}]") for i, l in enumerate(fn_layers)]
    fn_count  = len(validated)
    fn_list   = ", ".join(str(l) for l in validated)

    lines.append(f"#define FN_LAYER_COUNT {fn_count}")
    lines.append("")

    # Sentinel comment for convert_moonlander.py to extract values
    lines.append(f"// FN_LAYERS_VALUES: {fn_list}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    print("[led_config_gen] Leyendo configuración...")

    if not LED_CONFIG_FILE.exists():
        sys.exit(f"ERROR: No se encuentra {LED_CONFIG_FILE}")
    if not MAPPING_FILE.exists():
        sys.exit(f"ERROR: No se encuentra {MAPPING_FILE}")

    cfg     = load_json(LED_CONFIG_FILE)
    mapping = load_json(MAPPING_FILE)
    invert  = mapping.get("invert_layout", False)

    print(f"[led_config_gen] invert_layout = {invert}")

    content = generate(cfg, invert)

    KEYMAP_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(content, encoding="utf-8")

    print(f"[led_config_gen] Generado: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
