// Keymap config -- generado por convert_moonlander.py
// Defines portados del config.h Moonlander (ZSA-exclusivos omitidos).

// LED indicators override: include led_indicators.h generated by led_config_gen.py
#include "led_indicators.h"

#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define USB_SUSPEND_WAKEUP_DELAY 0
#define LAYER_STATE_16BIT
