// AUTO-GENERATED by led_config_gen.py — DO NOT EDIT
// Source: porting_zsa-moonlander/led_config/led_config.json
#pragma once

// ============================================================
// Connection mode LED indices
// (undef first to override keyboard-level config.h defaults)
// ============================================================
#undef  LED_USB_INDEX
#define LED_USB_INDEX 46
#undef  LED_BLE_1_INDEX
#define LED_BLE_1_INDEX 45
#undef  LED_BLE_2_INDEX
#define LED_BLE_2_INDEX 44
#undef  LED_BLE_3_INDEX
#define LED_BLE_3_INDEX 43
#undef  LED_2P4G_INDEX
#define LED_2P4G_INDEX 42

// BLE profile names
#undef  USER_BLE1_NAME
#define USER_BLE1_NAME "Geonix rev.2-1"
#undef  USER_BLE2_NAME
#define USER_BLE2_NAME "Geonix rev.2-2"
#undef  USER_BLE3_NAME
#define USER_BLE3_NAME "Geonix rev.2-3"

// ============================================================
// State indicator LEDs
// ============================================================
#undef  LED_CAP_INDEX
#define LED_CAP_INDEX 35
#undef  LED_WIN_L_INDEX
#define LED_WIN_L_INDEX 23
#undef  LED_BATT_INDEX
#define LED_BATT_INDEX 0

// ============================================================
// Battery bar (QK_BAT display)
// ============================================================
#undef  BATTERY_LED_COUNT
#define BATTERY_LED_COUNT     47
#undef  BATTERY_LED_ARRAY
#define BATTERY_LED_ARRAY     {11, 23, 35, 46, 10, 22, 34, 45, 9, 21, 33, 44, 8, 20, 32, 43, 7, 19, 31, 42, 6, 18, 30, 41, 5, 17, 29, 4, 16, 28, 40, 3, 15, 27, 39, 2, 14, 26, 38, 1, 13, 25, 37, 0, 12, 24, 36}
#undef  BATTERY_LOW_THRESHOLD
#define BATTERY_LOW_THRESHOLD 20
#undef  BATTERY_MED_THRESHOLD
#define BATTERY_MED_THRESHOLD 50

// ============================================================
// Layers that activate the connection mode indicator (Fn-held)
// ============================================================
#define FN_LAYER_COUNT 1

// FN_LAYERS_VALUES: 12
