// AUTO-GENERATED by led_config_gen.py — DO NOT EDIT
// Source: porting_zsa-moonlander/led_config/led_config.json
#pragma once

// ============================================================
// Connection mode LED indices
// (undef first to override keyboard-level config.h defaults)
// ============================================================
#undef  LED_USB_INDEX
#define LED_USB_INDEX 46
#undef  LED_BLE_1_INDEX
#define LED_BLE_1_INDEX 45
#undef  LED_BLE_2_INDEX
#define LED_BLE_2_INDEX 44
#undef  LED_BLE_3_INDEX
#define LED_BLE_3_INDEX 43
#undef  LED_2P4G_INDEX
#define LED_2P4G_INDEX 42

// BLE profile names
#undef  USER_BLE1_NAME
#define USER_BLE1_NAME "Geonix rev.2-1"
#undef  USER_BLE2_NAME
#define USER_BLE2_NAME "Geonix rev.2-2"
#undef  USER_BLE3_NAME
#define USER_BLE3_NAME "Geonix rev.2-3"

// ============================================================
// State indicator LEDs
// ============================================================
#undef  LED_CAP_INDEX
#define LED_CAP_INDEX 35
#undef  LED_WIN_L_INDEX
#define LED_WIN_L_INDEX 23
#undef  LED_BATT_INDEX
#define LED_BATT_INDEX 0

// ============================================================
// Battery bar (QK_BAT display)
// ============================================================
#undef  BATTERY_LED_COUNT
#define BATTERY_LED_COUNT     47
#undef  BATTERY_LED_ARRAY
#define BATTERY_LED_ARRAY     {11, 23, 35, 46, 10, 22, 34, 45, 9, 21, 33, 44, 8, 20, 32, 43, 7, 19, 31, 42, 6, 18, 30, 41, 5, 17, 29, 4, 16, 28, 40, 3, 15, 27, 39, 2, 14, 26, 38, 1, 13, 25, 37, 0, 12, 24, 36}
#undef  BATTERY_LOW_THRESHOLD
#define BATTERY_LOW_THRESHOLD 20
#undef  BATTERY_MED_THRESHOLD
#define BATTERY_MED_THRESHOLD 50

// ============================================================
// Battery Digits & Secondary Bar (QK_BAT2 display)
// ============================================================
#define BATTERY2_DIGIT_TENS_ARRAY {11, 23, 35, 10, 22, 34, 9, 21, 33, 8, 20, 32, 7, 19, 31}
#define BATTERY2_DIGIT_UNITS_ARRAY {4, 16, 28, 3, 15, 27, 2, 14, 26, 1, 13, 25, 0, 12, 24}

// Digit patterns (16-bit) mapping 3x5 grids (left-to-right, top-to-bottom)
#ifndef __ASSEMBLER__
#include <stdint.h>
/* 0: 0xF6D7, 1: 0x2C97, 2: 0x73E7, 3: 0x73CF, 4: 0x5BC9, 5: 0x79CF, 6: 0x79EF, 7: 0x7292, 8: 0x7BEF, 9: 0x7BCF */
static const uint16_t BATTERY2_DIGIT_PATTERNS[10] = {
    0xF6D7, 0x2C97, 0x73E7, 0x73CF, 0x5BC9,
    0x79CF, 0x79EF, 0x7292, 0x7BEF, 0x7BCF
};
#endif

#define BATTERY2_LED_COUNT     0
#define BATTERY2_LED_ARRAY     {}
#define BATTERY2_LOW_THRESHOLD 20
#define BATTERY2_MED_THRESHOLD 50

// ============================================================
// Layers that activate the connection mode indicator (Fn-held)
// ============================================================
#define FN_LAYER_COUNT 1

// FN_LAYERS_VALUES: 12
